version: '3'
services:
  pgtest_master:
    image: postgres:latest
    container_name: pgtest_master
    restart: always
    volumes:
        - ./db/data-master:/var/lib/postgresql/data
        - ./db/tmp-master:/tmp
    ports:
      - '5454:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=pass@123'
      - 'POSTGRES_DB=postgres'

  pgtest_standby:
    image: postgres:latest
    container_name: pgtest_standby
    restart: always
    volumes:
        - ./db/data-standby:/var/lib/postgresql/data
        - ./db/tmp-standby:/tmp
    ports:
      - '5455:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=pass@123'
      - 'POSTGRES_DB=postgres'