version: "3"
services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 1234

    ports:
        # The standard AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    