version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs
    command: "master -ip=master -ip.bind=0.0.0.0 -volumeSizeLimitMB=1024"
    stop_grace_period: 1s

  volume:
    image: chrislusf/seaweedfs
    command: 'volume -mserver="master:9333" -index=leveldb -ip.bind=0.0.0.0 -dir=/data/ -max=0 -fileSizeLimitMB=32'
    depends_on:
      - master
    volumes:
      - ./seaweedfs:/data/
    stop_grace_period: 1s

  filer:
    image: chrislusf/seaweedfs
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0'
    ports:
      - 8888:8888
    depends_on:
      - master
      - volume
    stop_grace_period: 1s

  s3:
    image: chrislusf/seaweedfs
    ports:
      - 8333:8333
    command: 's3 -config=/config.json -filer="filer:8888" -ip.bind=0.0.0.0'
    volumes:
      - ./seaweedfs-s3-config.json:/config.json:ro
    depends_on:
      - master
      - volume
      - filer
    stop_grace_period: 1s